version: "0.1.0.{build}"

test: off

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MyGet


# Master configuration (does deploy)
-
	branches:
	  only:
	    - master

	configuration: Release

	deploy:
	- provider: NuGet
	  server: https://www.myget.org/F/mendham/api/v2
	  api_key:
	    secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
	  symbol_server: https://nuget.symbolsource.org/MyGet/mendham
	  artifact: MyGet

# Dev configuration (just builds and tests)
- 
	branches:
	  only:
	    - dev

	configuration: Debug
