# Master configuration (does deploy)
-
 branches:
  only:
   - master

 version: "0.1.0.{build}"

 test: off

 cache:
  - %USERPROFILE%\.dnx

 services:
  - mssql2014

 build_script:
 - ps: .\build.ps1

 artifacts:
 - path: artifacts\packages\**\*.nupkg
   name: MendhamPackages

 configuration: Release

 deploy:
 - provider: NuGet
   server: https://www.myget.org/F/mendham/api/v2
   api_key:
     secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
   symbol_server: https://nuget.symbolsource.org/MyGet/mendham
   artifact: MendhamPackages
   on:
    branch: master

 - provider: GitHub
   release: Mendham 0.1.0-alpha-build$(appveyor_build_version)
   artifact: /.*\.nupkg/ 
   auth_token:
    secure: X5coKvPlCFPeRzwFfSopbB8jO8doWfNmx9p9g8yp1AsUKz4QLUtaNYwjwwLDAPPk
   prerelease: true
   on:
    branch: master
    appveyor_repo_tag: true

 - provider: NuGet
   api_key:
     secure: 7FiludlzP0brUSV6CsRH2QbiXSgvd35Kcpm+ruj0WGx05Q+CF7X+0sf5ylMwLHhi
   skip_symbols: true
   artifact: MendhamPackages
   on:
    branch: master
    appveyor_repo_tag: true


# Dev configuration (just builds and tests)
- 
 branches:
  only:
   - dev

 version: "0.1.0.{build}-dev"

 test: off

 cache:
  - %USERPROFILE%\.dnx

 services:
  - mssql2014

 build_script:
 - ps: .\build.ps1

 artifacts:
 - path: artifacts\packages\**\*.nupkg
   name: MyGet

 configuration: Debug