version: "0.1.0.{build}"

os: Visual Studio 2015

test: off

install:
- ps: >-
    nuget update -self
    Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"
    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
    & .\dotnet-install.ps1 -Channel "preview" -Version "1.0.0-preview2-003121" -InstallDir "$env:DOTNET_INSTALL_DIR"

services:
- mssql2014

branches:
  except:
    - /gh-pages.*/

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MendhamPackages

configuration: Release

deploy:
- provider: NuGet
  server: https://www.myget.org/F/mendham/api/v2/package
  api_key:
    secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
  skip_symbols: false
  artifact: MendhamPackages
  symbol_server: https://www.myget.org/F/mendham/api/v2/package
  on:
    branch: master

- provider: NuGet
  server: https://www.myget.org/F/mendham/api/v2/package
  api_key:
    secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
  skip_symbols: false
  artifact: MendhamPackages
  symbol_server: https://www.myget.org/F/mendham/api/v2/package
  on:
    appveyor_repo_tag: true

- provider: NuGet
  api_key:
    secure: 7FiludlzP0brUSV6CsRH2QbiXSgvd35Kcpm+ruj0WGx05Q+CF7X+0sf5ylMwLHhi
  skip_symbols: true
  artifact: MendhamPackages
  on:
    appveyor_repo_tag: true