version: "0.1.0.{build}"

test: off

services:
- mssql2014

branches:
  only:
    - master

  except:
    - /gh-pages.*/

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MendhamPackages

configuration: Release

deploy:
- provider: NuGet
  server: https://www.myget.org/F/mendham/api/v3/index.json
  api_key:
    secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: false

- provider: NuGet
  api_key:
    secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
  symbol_server: https://www.myget.org/F/mendham/api/v3/index.json
  artifact: MendhamPackages
  on:
    branch: master
    appveyor_repo_tag: false
