version: "0.1.0.{build}"

test: off

services:
- mssql2014

branches:
  only:
    - master

  except:
    - /gh-pages.*/

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MendhamPackages

configuration: Release

deploy:
- provider: NuGet
  server: https://www.myget.org/F/mendham/api/v2/package
  api_key:
    secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
  skip_symbols: false
  artifact: MendhamPackages
  symbol_server: https://www.myget.org/F/mendham/api/v2/package
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: 7FiludlzP0brUSV6CsRH2QbiXSgvd35Kcpm+ruj0WGx05Q+CF7X+0sf5ylMwLHhi
  skip_symbols: true
  artifact: MendhamPackages
  on:
    branch: master
    appveyor_repo_tag: true