version: "0.1.0.{build}"

test: off

services:
- mssql2014

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MendhamPackages

configuration: Release

deploy:
- provider: NuGet
  server: https://www.myget.org/F/mendham/api/v2
  api_key:
    secure: lc6qh+UNxNqcweligghUHBrdF22ErLbrckDPGQB0W0CF+jH+EeP0ZnZCwGkl0wg9
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: false

- provider: NuGet
  api_key:
    secure: 7FiludlzP0brUSV6CsRH2QbiXSgvd35Kcpm+ruj0WGx05Q+CF7X+0sf5ylMwLHhi
  symbol_server: https://nuget.symbolsource.org/MyGet/mendham
  artifact: MendhamPackages
  on:
   branch: master
   appveyor_repo_tag: true